server:
  port: 8078

spring:
  mail:
    host: smtp.qq.com
    username: 895970721@qq.com
    password: okscnlceazjmbfhi
    properties:
      mail:
        smtp:
          ssl:
            enable:
              true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
    default-encoding: utf-8

bill:
  electricity:
      accountList:
        - {toEmail: "895970721@qq.com", supplierId: 901002, accountNo: "0000007828"}

mail:
  from: "895970721@qq.com"

